export {default as NavBar} from './navbar';
export {default as Login} from './login';
export {default as SignUp} from './signup';
export {default as Global} from './global';
export {default as Profile} from './profile';
export {default as Edit} from './edit';
export {default as SeeEvaRes} from './seeEvaRes'
export {default as CreateEvaluationForm} from './createevaluationform';
export {default as Home} from './home';
export {default as EnrollCourse} from './enrollcourse';
