export { default as NavBar } from "./navbar";
export { default as Login } from "./login";
export { default as SignUp } from "./signup";
export { default as Global } from "./global";
export { default as Profile } from "./profile";
export { default as Edit } from "./edit";
export { default as SeeEvaRes } from "./seeEvaRes";
export { default as CreateEvaluationForm } from "./createevaluationform";
export { default as Home } from "./home";
export { default as EnrollCourse } from "./enrollcourse";
export { default as SeeCourses } from "./seecourses";
export {default as Accounts} from './accounts';
export {default as AddSemester} from './addSemester';
export {default as AddCourse} from './addCourse';
export {default as ForgetPassword} from './forgetPassword';